#!/usr/bin/env python3
"""Push measured timing into the hand-authored HyperFrames files.

Compositions keep their bespoke art direction and their own motion logic;
only the numbers come from measurement. Each composition receives a
generated block holding the chapter duration and a `BEATS` table, so a
keyframe is written as `show("pg-v1", B("S42.1"))` instead of a literal
second that has to be recomputed by hand after every re-record.

Chapter index files get their caption cues replaced the same way.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

BEGIN = "/* timing:start — generated by apply_timing.py, do not edit */"
END = "/* timing:end */"

HELPERS = """function B(id, offset) {
  var b = BEATS[id];
  if (!b) throw new Error("unknown beat: " + id);
  return b.start + (offset || 0);
}
function BE(id, offset) {
  var b = BEATS[id];
  if (!b) throw new Error("unknown beat: " + id);
  return b.end + (offset || 0);
}
/* Anchor to a spoken phrase inside a line, for enumerations named in one
   sentence. W is when the phrase starts, WE when it finishes. */
function W_(id, phrase) {
  var b = BEATS[id];
  if (!b) throw new Error("unknown beat: " + id);
  var key = phrase.replace(/[\\s，。？！：；、,.?!:;「」“”‘’（）()《》—…·-]/g, "");
  var i = b.t.indexOf(key);
  if (i < 0) throw new Error("phrase not in " + id + ": " + phrase);
  return [b, i, key.length];
}
function W(id, phrase, offset) {
  var f = W_(id, phrase);
  return f[0].s[f[1]] + (offset || 0);
}
function WE(id, phrase, offset) {
  var f = W_(id, phrase);
  return f[0].e[f[1] + f[2] - 1] + (offset || 0);
}"""

D_RE = re.compile(r"^const D = ([0-9.]+);\s*$", re.MULTILINE)
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
CUES_RE = re.compile(r"^const cues = .*?;\s*$", re.MULTILINE)



def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def block_for(duration: float, beats: dict) -> str:
    table = json.dumps(beats, ensure_ascii=False, indent=0).replace("\n", "")
    return (
        f"{BEGIN}\n"
        f"const D = {duration:.3f};\n"
        f"const BEATS = {table};\n"
        f"{HELPERS}\n"
        f"{END}"
    )


def apply_block(path: Path, duration: float, beats: dict) -> str:
    html = path.read_text(encoding="utf-8")
    block = block_for(duration, beats)

    if BLOCK_RE.search(html):
        old_d = float(D_RE.search(BLOCK_RE.search(html).group(0)).group(1))
        html = BLOCK_RE.sub(lambda _: block, html, count=1)
    else:
        match = D_RE.search(html)
        if not match:
            raise SystemExit(f"{path.name}: no 'const D = ...;' to anchor the block")
        old_d = float(match.group(1))
        html = html[: match.start()] + block + "\n" + html[match.end():]

    # Duration also appears as clip metadata in the chapter index hosts.
    if abs(old_d - duration) > 1e-6:
        html = html.replace(f'data-duration="{old_d:.3f}"', f'data-duration="{duration:.3f}"')
        html = html.replace(f'data-duration="{old_d:g}"', f'data-duration="{duration:.3f}"')
    path.write_text(html, encoding="utf-8")
    return f"D {old_d:.3f} -> {duration:.3f}, {len(beats)} beats"


def apply_cues(path: Path, cues: list[dict]) -> str:
    html = path.read_text(encoding="utf-8")
    if not CUES_RE.search(html):
        raise SystemExit(f"{path.name}: no 'const cues = ...;' line found")
    payload = json.dumps(
        [{"start": c["start"], "end": c["end"], "text": c["text"]} for c in cues],
        ensure_ascii=False,
    )
    html = CUES_RE.sub(lambda _: f"const cues = {payload};", html, count=1)
    path.write_text(html, encoding="utf-8")
    return f"{len(cues)} cues"


ANCHOR_CALL_RE = re.compile(r"\b(?:B|BE|W|WE)\([^()]*\)")
LITERAL_RE = re.compile(r"(?:,|\[)\s*(\d+\.\d+)\s*(?=[,)\]])")


def literal_times(path: Path) -> list[str]:
    """Report keyframe times still written as bare seconds.

    Offsets inside an anchor call are relative to a measured beat and move
    with it, so they are not literals in the sense that matters here. Zero is
    the composition's own start, which no re-record can shift.
    """
    body = BLOCK_RE.sub("", path.read_text(encoding="utf-8"))
    body = ANCHOR_CALL_RE.sub("", body)
    return [m.group(1) for m in LITERAL_RE.finditer(body) if float(m.group(1)) != 0.0]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--project", required=True, type=Path)
    ap.add_argument("--chapters", nargs="*")
    args = ap.parse_args()

    project: Path = args.project
    beats_doc = load(project / "timing/beats.json")
    chapters = load(project / "timing/chapters.json")["chapters"]
    comps = project / "hyperframes/compositions"
    indexes = project / "hyperframes/_chapter-indexes"

    stale = []
    for chapter_id in (args.chapters or sorted(chapters)):
        duration = float(chapters[chapter_id]["duration"])
        aligned = load(project / f"timing/align/{chapter_id}.json")
        chars = {u["id"]: u["chars"] for u in aligned["units"]}
        beats = {}
        for bid, b in beats_doc["beats"].items():
            if b["chapter"] != chapter_id:
                continue
            entry = {"start": b["start"], "end": b["end"]}
            spoken = chars.get(bid, [])
            if spoken:
                entry["t"] = "".join(c["c"] for c in spoken)
                entry["s"] = [c["start"] for c in spoken]
                entry["e"] = [c["end"] for c in spoken]
            beats[bid] = entry

        comp = comps / f"{chapter_id}.html"
        if comp.exists():
            print(f"{comp.name}: {apply_block(comp, duration, beats)}")
            leftovers = literal_times(comp)
            if leftovers:
                stale.append((comp.name, leftovers))

        index = indexes / f"index-{chapter_id}.html"
        if index.exists():
            cues = load(project / f"timing/cues/{chapter_id}.json")["cues"]
            print(f"{index.name}: {apply_block(index, duration, beats)}, "
                  f"{apply_cues(index, cues)}")

    if stale:
        print("\nStill anchored to literal seconds, so a re-record will not "
              "reach them:", file=sys.stderr)
        for name, values in stale:
            preview = ", ".join(values[:8]) + (" ..." if len(values) > 8 else "")
            print(f"  {name}: {len(values)} ({preview})", file=sys.stderr)


if __name__ == "__main__":
    main()
